### ISSUE TITLE
스택/큐 + 그리디

### ISSUE THREAD

**Issue by yeeuniii** [yeeuniii/python-algorithm#11]
# ToDo
- [ ] 책 8장 탐욕 알고리즘. 그리디 개념 정리
- [ ] 스택 / 큐 벨로그 추가 정리

## 문제 풀이
- 스택/큐
- [ ]  프로그래머스. 주식 가격
- [ ]  프로그래머스. 프린터
- 그리디
- [ ]  백준 11399 ATM 
- [ ]  백준 1931 회의실 배정 
- [ ]  백준 12845 모두의 마블 
- [ ]  백준 11047 동전 0 
## 오답노트
- 스택/큐
- [ ] 백준 1966 프린터 큐
